modLoader = "javafml"
loaderVersion = "[${neo_major_version},)"
issueTrackerURL = "https://github.com/pharuxtan/woot"
license = "LGPLv3"

[[mods]]
modId = "${file.modId}"
version = "${file.jarVersion}"
displayName = "Woot Revived"
displayURL = "https://github.com/pharuxtan/woot"
logoFile = "woot_revived.png"
authors = "pharuxtan"
credits = "Ipsis"
description = '''A formidable multiblock mod to harvest mob drops. You'll either fall in love or despise it! No middle ground.'''

[[dependencies.${file.modId}]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "${mc_version}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${file.modId}]]
modId = "forge"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${file.modId}]]
modId="guideme"
mandatory = true
versionRange = "[${guideme_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${file.modId}]]
modId="jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${file.modId}]]
modId="jade"
mandatory = false
versionRange = "[${jade_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${file.modId}]]
modId="kubejs"
mandatory = false
versionRange = "[${kubejs_version},)"
ordering="NONE"
side="BOTH"
